In [1]:
import pandas as pd

csvName = "Tweets.csv"
df = pd.read_csv(csvName)
df.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)

In [2]:
set_airline = set(df['airline'])
print(set_airline)

{'US Airways', 'Delta', 'American', 'Virgin America', 'Southwest', 'United'}

In [3]:
print(len(df[df.airline == "US Airways"]))
print(len(df[df.airline == "American"]))
print(len(df[df.airline == "United"]))
print(len(df[df.airline == "Delta"]))
print(len(df[df.airline == "Southwest"]))
print(len(df[df.airline == "Virgin America"]))

2913
2759
3822
2222
2420
504

In [4]:
df2 = df[(df.airline_sentiment == "negative") & (df.airline == "US Airways")]
df2.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
8966,570310600460525568,negative,0.6292,Flight Booking Problems,0.3146,US Airways,NaN,jhazelnut,NaN,0,@USAirways is there a better time to call? My...,NaN,2015-02-24 11:53:37 -0800,NaN,NaN
8967,570310144459972608,negative,1.0000,Customer Service Issue,1.0000,US Airways,NaN,GAKotsch,NaN,0,@USAirways and when will one of these agents b...,NaN,2015-02-24 11:51:48 -0800,NaN,Atlantic Time (Canada)
8970,570308799950692353,negative,1.0000,Customer Service Issue,0.6452,US Airways,NaN,retardedlarry,NaN,0,@USAirways just hung up on me again. Another ...,NaN,2015-02-24 11:46:28 -0800,NaN,NaN
8972,570307605631012864,negative,1.0000,Customer Service Issue,1.0000,US Airways,NaN,Matt_Bernanke,NaN,0,@USAirways you're killing me from the inside,NaN,2015-02-24 11:41:43 -0800,NaN,Quito
8973,570307109218340865,negative,0.7020,Flight Attendant Complaints,0.7020,US Airways,NaN,jeremyleewhite,NaN,0,@USAirways is not the new @AmericanAir is more...,"[35.21979387, -80.94498281]",2015-02-24 11:39:45 -0800,NaN,NaN

In [5]:
df2["text"].to_csv("negetiveText_" + "US_Airways" + ".txt", header=False, index=False)